[package]
name = "ai-heroes-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Pricop George <pricopgeorge@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ai-heroes = { path = ".." }
multiversx-sc-wasm-adapter = "0.47.0"

[workspace]
