// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ai_heroes
    (
        init => init
        upgrade => upgrade
        setPaused => set_paused
        setAIEndpoint => set_ai_endpoint
        setGameSetting => set_game_setting
        withdrawFees => withdraw_fees
        generateAIHero => generate_ai_hero
        generateBasicHero => generate_basic_hero
        getTotalHeroes => get_total_heroes
        getContractInfo => get_contract_info
        getTotalRevenue => get_total_revenue
        getRevenueByType => get_revenue_by_type
        emergencyPause => emergency_pause
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
